[package]
name = "evaluate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
robusta_jni = "0.2.2"
zen-engine = "0.33.0"
serde_json = "1.0.132"
futures = "0.3.31"
uuid = { version = "1.11.0", features = ["v4"] }