name: DEV - Application Build
on:
  workflow_dispatch:
env:
  RUST_BACKTRACE: 'full'
jobs:
  build:
    name: "Build Jar"
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - run: mkdir libs && cp -r target/classes/io/doraig/libs/* library
      - uses: actions/upload-artifact@v4
        with:
          name: Package_${{matrix.os}}
          path: staging
      - uses: actions/upload-artifact@v4
        with:
          name: Library_${{matrix.os}}
          path: library



