name: Build and Package Jar
on:
  workflow_dispatch:
env:
  RUST_BACKTRACE: 'full'
jobs:
  build:
    name: "Build Jar"
    strategy:
        matrix:
          include:
            - os: ubuntu-latest
              arch: "x86_64"
            - os: macos-13
              arch: "x86_64"
            - os: macos-latest
              arch: "arm64"
            - os: windows-latest
              arch: "x86_64"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - run: mkdir -p io/doraig/libs && cp -r target/classes/io/doraig/libs/* io/doraig/libs/
      - uses: actions/upload-artifact@v4
        with:
          name: Package_${{matrix.os}}_${{matrix.arch}}
          path: staging
      - uses: actions/upload-artifact@v4
        with:
          name: Library_${{matrix.os}}_${{matrix.arch}}
          path: io/doraig/libs
  repackage:
    name: "Repackage Jar"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - uses: actions/download-artifact@v4
        with:
          path: repackage
          pattern: Library_*
      - uses: actions/download-artifact@v4
        with:
          path: repackage
          name: Package_ubuntu-latest_x86_64
      - name: Perform repackage
        run: |
          cd repackage && mkdir -p io/doraig/libs && cp -r Library_*/* io/doraig/libs/
          jar -uf *-jar-with-dependencies.jar io/doraig/libs
          mkdir -p ../repackaged && cp *-jar-with-dependencies.jar ../repackaged
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: repackaged
  release:
    name: "Release Jar"
    needs: repackage
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/download-artifact@v4
        with:
          path: artifact
          name: Package
      - name: Upload  release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact
          asset_name: zen-java-engine-${{ steps.version.outputs.version }}-jar-with-dependencies.jar
          asset_content_type: application/java-archive




