name: Prepare release
on:
  workflow_dispatch:
env:
  RUST_BACKTRACE: 'full'
  MAVEN_GPG_PASSPHRASE: ${{ secrets.PASS_PHARASE }}
  MAVEN_GPG_KEY: ${{ secrets.SIGN_KEY }}
jobs:
  build:
    name: "Prepare release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn release:update-versions
          mvn release:prepare