name: Prepare release
on:
  workflow_dispatch:
env:
  RUST_BACKTRACE: 'full'
jobs:
  build:
    name: "Prepare release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn release:prepare